name: Publish Dotnet Layers

on:
  push:
    tags:
      - v**_dotnet

jobs:
  publish-dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Check Tag
        id: dotnet-check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+(\.[0-9]+)*_dotnet ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64, amd64
      - name: Publish Dotnet Layer
        if: steps.dotnet-check-tag.outputs.match == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AGENT_VERSION: ${{ steps.dotnet-check-tag.outputs.version }}
        run: |
          cd dotnet
          ./publish-layers.sh
