name: Snyk Vulnerability Scanning (With Nav)

on:
  workflow_dispatch:
  
jobs:
  security:
    runs-on: ubuntu-latest
    container: "docker://snyk/snyk:gradle-jdk8"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: 'master'
      
      - name: Setup Authentication
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
    
      - name: Run Snyk Dependency Scan
        run: |
          cd java
          snyk monitor --all-sub-projects --org=java-agent-test --configuration-matching='(^compileClasspath$)|(^runtimeClasspath$)'

