name: Snyk Vulnerability Scan - Navigating to Project
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: 'master'

      # - name: Navigate to Java Directory
      #   run: cd java

      # - name: List Current Dir After Navigation
      #   run: ls -a
    
      - name: Run Snyk To Check For Vulnerabilities
        uses: snyk/actions/gradle-jdk11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --configuration-matching='(^compileClasspath$)|(^runtimeClasspath$)'
