# This workflow automates the process of identifying potential security vulnerabilities 
# using Snyk. Dependency vulnerability scans will be run when a push is made to the main 
# branch, on a weekly schedule, and can also be triggered manually.

name: Snyk Vulnerability Scan
on:
  workflow_dispatch:
  schedule:
  - cron: '00 15 * * 1'
  push:
    branches:
      - master

jobs:
  security:
    name: Run Snyk To Check For Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: 'master'
          
      - name: Navigate to Java Directory
        run: |
          cd $GITHUB_WORKSPACE/java
          snyk monitor --org=java-agent-test --configuration-matching='(^compileClasspath$)|(^runtimeClasspath$)'

      # - name: List Current Dir Files
      #   run: ls -a
        
      # - name: Run Snyk Scan
      #   uses: snyk/actions/gradle@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     command: monitor
      #     working-drirectory: java
      #     # args: --org=java-agent-test --file=$GITHUB_WORKSPACE/java/build.gradle --configuration-matching='(^compileClasspath$)|(^runtimeClasspath$)'
      #     args: --org=java-agent-test --all-sub-projects --configuration-matching='(^compileClasspath$)|(^runtimeClasspath$)'
