# This workflow automates the process of identifying potential security vulnerabilities 
# using Snyk. Dependency vulnerability scans will be run when a push is made to the main 
# branch, on a weekly schedule, and can also be triggered manually.

name: Snyk Vulnerability Scan
on:
  workflow_dispatch:
  schedule:
  - cron: '00 15 * * 1'
  push:
    branches:
      - master

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: List Environment Variables
        run: env

      - name: Debug - List Files in Java Directory
        run: ls -al java

      - name: Navigate to Java Directory
        run: cd $GITHUB_WORKSPACE/java

      - name: Debug - Start Interactive Debug Session
        run: /bin/bash
        env:
          GITHUB_WORKSPACE: $GITHUB_WORKSPACE
    
      - name: Run Snyk To Check For Vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --org=java-agent-test --configuration-matching='(^compileClasspath$)|(^runtimeClasspath$)'
