# This workflow automates the process of identifying potential security vulnerabilities 
# using Snyk. Dependency vulnerability scans will be run when a push is made to the main 
# branch, on a weekly schedule, and can also be triggered manually.

name: Snyk Vulnerability Scan
on:
  workflow_dispatch:
  schedule:
  - cron: '00 15 * * 1'
  push:
    branches:
      - master

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: 'master'
          
      # - name: Navigate to Java Directory
      #   run: cd $GITHUB_WORKSPACE/java/

      # - name: List Current Dir Files
      #   run: ls -a
        
      - name: Run Snyk To Check For Vulnerabilities
        uses: snyk/actions/gradle-jdk11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          entryPoint: $GITHUB_WORKSPACE/java/
          # args: --org=java-agent-test --file=$GITHUB_WORKSPACE/java/build.gradle --configuration-matching='(^compileClasspath$)|(^runtimeClasspath$)'
          args: --org=java-agent-test --all-sub-projects --configuration-matching='(^compileClasspath$)|(^runtimeClasspath$)'
